---
- name: Running the software clean command
  ios_command:
    commands:
      - command: 'install remove inactive'
        prompt: 'Do you want to remove the above files?'
        answer: 'y'
  when: really_delete_files|bool
  register: command_results
